name: Run Prettier
on:
  workflow_dispatch:
  pull_request:
jobs:
  run-coverage:
    name: Run Prettier
    runs-on: ubuntu-latest
    env:
      ETHERSCAN_KEY: ${{ secrets.ETHERSCAN_KEY }}
      INFURA_KEY: ${{ secrets.INFURA_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          cache: 'yarn'
          node-version: '16'

      - name: Install packages
        run: yarn install --non-interactive --frozen-lockfile && yarn build

      - name: Run Prettier
        run: yarn run prettier --check .
