name: 'Run Spider'
on:
  workflow_dispatch:
  pull_request:
jobs:
  run_spider:
    name: Run Spider
    runs-on: ubuntu-latest
    env:
      ETHERSCAN_KEY: ${{ secrets.ETHERSCAN_KEY }}
      SNOWTRACE_KEY: ${{ secrets.SNOWTRACE_KEY }}
      INFURA_KEY: ${{ secrets.INFURA_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install packages
        run: yarn install --non-interactive --frozen-lockfile

      - name: Run Spider
        run: |
          for k in `ls deployments | grep -v .ts`; do yarn hardhat spider --network $k; done

      - uses: actions/upload-artifact@v2
        with:
          name: deployments
          path: deployments/
          retention-days: 365 # TODO: should we have another flow to copy to permanent release?

