name: Scenario Report
on:
  workflow_run:
    workflows: ['Run Scenarios']  # runs after CI workflow
    types:
      - completed
jobs:
  scenario-report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: scenario-results        # Artifact name
        name: Scenario Tests              # Name of the check run which will be created
        path: 'scenario-results.json'     # Path to test results (inside artifact .zip)
        reporter: mocha-json              # Format of test results
