name: 'Test Report'
on:
  workflow_run:
    workflows: ['Run Unit Tests']  # runs after CI workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - uses: dorny/test-reporter@v1
      with:
        artifact: test-results            # artifact name
        name: Unit Tests                  # Name of the check run which will be created
        path: 'xunit.xml'                 # Path to test results (inside artifact .zip)
        reporter: jest-junit              # Format of test results
